Setup project page
jetthoughts/gh_metrics pull request #7
Opened 2017-01-24 15:02 UTC by katlavan

2017-01-24 15:57 UTC, katlavan commented
@loogle18 Please verify

2017-01-24 16:30 UTC, ultroned reviewed
Please do rebase if you did not it and consider my comments.
@m-k please check it too. I could mess something.

2017-01-24 16:30 UTC, loogle18 commented on app/assets/javascripts/components/chart.es6
> +        console.log('Error : ', err);
Add basic alert or remove this.

2017-01-24 16:30 UTC, loogle18 commented on app/views/setup/index.haml
> +.project-selection.js-project-selection{ 'data-url': update_labels_path}
Add space before last bracket.

2017-01-24 16:30 UTC, loogle18 commented on app/views/setup/index.haml
> +  = select_tag 'backlog', options_for_select(@repositories), id: :project_selection
Why not class instead id?

2017-01-24 16:30 UTC, loogle18 commented on app/controllers/setup_controller.rb
> +  def load_labels_content(labels)
```
if load_events.exists?
    render_to_string( partial: 'setup/labels' ,  collection: @labels.label_status, as: :label,
                      locals: { select_options: @labels.labels_name_list })
else
    I18n.t('no_labels')
end
```

2017-01-24 16:30 UTC, loogle18 commented on app/controllers/setup_controller.rb
> +  def load_repositories
It's duplication, please move to protected method of application controller, and just call it.
And remove this logic from metrics controller as well.

2017-01-24 16:30 UTC, loogle18 commented on app/controllers/setup_controller.rb
> +  def load_events
It's duplication, please move to protected method of application controller, and just call it.
And remove this logic from metrics controller as well.

2017-01-24 16:30 UTC, loogle18 commented on app/controllers/setup_controller.rb
> +      Event.where(repo: params[:repository])
And add `created` params like [here](https://github.com/jetthoughts/gh_metrics/pull/4/files#diff-12435b1e4e29226967cae794fbffb44cR21)

2017-01-24 16:50 UTC, katlavan commented
@loogle18 Fixed. Please recheck

2017-01-24 17:11 UTC, m-k requested changes
@katlavan please consider by comments.

2017-01-24 17:11 UTC, m-k commented on app/views/layouts/_topbar.haml
> +        %li= link_to 'Setup Repositrory', setup_path, class: 'right'
Setup Reposit~r~ory 🇬🇧 

Please move all texts to translations.

Also, this button should move us to editing current repository or be `Setup repositories`.

2017-01-24 17:11 UTC, m-k commented on app/views/setup/index.haml
> +                                locals: { select_options: @labels.labels_name_list }
Please fix formatting.

2017-01-25 09:57 UTC, katlavan commented
@m-k Fixed. Please recheck.

2017-01-31 10:04 UTC, m-k commented on app/controllers/setup_controller.rb
> +
please remove empty line

2017-01-31 10:08 UTC, katlavan commented
@m-k Done. Please recheck

2017-01-31 10:18 UTC, m-k requested changes
@katlavan please consider my comments.

2017-01-31 10:18 UTC, m-k commented on app/carriers/labels_carrier.rb
> +  LABEL_STATUS = %w(backlog ready progress verify codereview)
Freeze mutable objects assigned to constants

2017-01-31 10:18 UTC, m-k commented on app/carriers/labels_carrier.rb
> +    uniq_labels.map{|l| l[:name]}
Please add spaces inside `{}`

2017-01-31 10:18 UTC, m-k commented on app/carriers/labels_carrier.rb
> +    @label_status = LABEL_STATUS
No need to use instance variable, please use `LabelsCarrier::LABEL_STATUS` in views.

2017-01-31 10:18 UTC, m-k commented on app/controllers/setup_controller.rb
> +
✂️

2017-01-31 10:18 UTC, m-k commented on app/controllers/setup_controller.rb
> +                        locals: { select_options: @labels.labels_name_list })
please remove spaces
```
render_to_string( partial: 'setup/labels' ,  collection: @labels.label_status, as: :label,
                 ^                       ^ ^
```

2017-01-31 10:18 UTC, m-k commented on config/locales/en.yml
> +    app_name: "Github Metrics"
Prefer single-quoted strings when you don't need string interpolation or special symbols.

2017-01-31 10:24 UTC, katlavan commented
@m-k Done. Please recheck.

2017-01-31 10:26 UTC, m-k approved these changes

2017-01-31 10:27 UTC, merged